from setuptools import setup

setup(
    name='gvb',
    version='3.0',
    packages=['gvb', 'venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing._private',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.scipy', 'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.signal.windows', 'venv.Lib.site-packages.scipy.sparse',
              'venv.Lib.site-packages.scipy.sparse.tests', 'venv.Lib.site-packages.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.spatial.transform',
              'venv.Lib.site-packages.scipy.spatial.transform.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.optimize._shgo_lib',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.sympy', 'venv.Lib.site-packages.sympy.core',
              'venv.Lib.site-packages.sympy.core.tests', 'venv.Lib.site-packages.sympy.core.benchmarks',
              'venv.Lib.site-packages.sympy.sets', 'venv.Lib.site-packages.sympy.sets.tests',
              'venv.Lib.site-packages.sympy.sets.handlers', 'venv.Lib.site-packages.sympy.logic',
              'venv.Lib.site-packages.sympy.logic.tests', 'venv.Lib.site-packages.sympy.logic.utilities',
              'venv.Lib.site-packages.sympy.logic.algorithms', 'venv.Lib.site-packages.sympy.polys',
              'venv.Lib.site-packages.sympy.polys.agca', 'venv.Lib.site-packages.sympy.polys.agca.tests',
              'venv.Lib.site-packages.sympy.polys.tests', 'venv.Lib.site-packages.sympy.polys.domains',
              'venv.Lib.site-packages.sympy.polys.domains.tests', 'venv.Lib.site-packages.sympy.polys.benchmarks',
              'venv.Lib.site-packages.sympy.stats', 'venv.Lib.site-packages.sympy.stats.tests',
              'venv.Lib.site-packages.sympy.unify', 'venv.Lib.site-packages.sympy.unify.tests',
              'venv.Lib.site-packages.sympy.crypto', 'venv.Lib.site-packages.sympy.crypto.tests',
              'venv.Lib.site-packages.sympy.series', 'venv.Lib.site-packages.sympy.series.tests',
              'venv.Lib.site-packages.sympy.series.benchmarks', 'venv.Lib.site-packages.sympy.tensor',
              'venv.Lib.site-packages.sympy.tensor.array', 'venv.Lib.site-packages.sympy.tensor.array.tests',
              'venv.Lib.site-packages.sympy.tensor.tests', 'venv.Lib.site-packages.sympy.vector',
              'venv.Lib.site-packages.sympy.vector.tests', 'venv.Lib.site-packages.sympy.codegen',
              'venv.Lib.site-packages.sympy.codegen.tests', 'venv.Lib.site-packages.sympy.ntheory',
              'venv.Lib.site-packages.sympy.ntheory.tests', 'venv.Lib.site-packages.sympy.parsing',
              'venv.Lib.site-packages.sympy.parsing.latex', 'venv.Lib.site-packages.sympy.parsing.latex._antlr',
              'venv.Lib.site-packages.sympy.parsing.tests', 'venv.Lib.site-packages.sympy.parsing.autolev',
              'venv.Lib.site-packages.sympy.parsing.autolev._antlr',
              'venv.Lib.site-packages.sympy.parsing.autolev.test-examples',
              'venv.Lib.site-packages.sympy.parsing.autolev.test-examples.pydy-example-repo',
              'venv.Lib.site-packages.sympy.physics', 'venv.Lib.site-packages.sympy.physics.hep',
              'venv.Lib.site-packages.sympy.physics.hep.tests', 'venv.Lib.site-packages.sympy.physics.tests',
              'venv.Lib.site-packages.sympy.physics.units', 'venv.Lib.site-packages.sympy.physics.units.tests',
              'venv.Lib.site-packages.sympy.physics.units.systems', 'venv.Lib.site-packages.sympy.physics.optics',
              'venv.Lib.site-packages.sympy.physics.optics.tests', 'venv.Lib.site-packages.sympy.physics.vector',
              'venv.Lib.site-packages.sympy.physics.vector.tests', 'venv.Lib.site-packages.sympy.physics.quantum',
              'venv.Lib.site-packages.sympy.physics.quantum.tests', 'venv.Lib.site-packages.sympy.physics.mechanics',
              'venv.Lib.site-packages.sympy.physics.mechanics.tests',
              'venv.Lib.site-packages.sympy.physics.continuum_mechanics',
              'venv.Lib.site-packages.sympy.physics.continuum_mechanics.tests', 'venv.Lib.site-packages.sympy.sandbox',
              'venv.Lib.site-packages.sympy.sandbox.tests', 'venv.Lib.site-packages.sympy.solvers',
              'venv.Lib.site-packages.sympy.solvers.tests', 'venv.Lib.site-packages.sympy.solvers.benchmarks',
              'venv.Lib.site-packages.sympy.algebras', 'venv.Lib.site-packages.sympy.algebras.tests',
              'venv.Lib.site-packages.sympy.calculus', 'venv.Lib.site-packages.sympy.calculus.tests',
              'venv.Lib.site-packages.sympy.concrete', 'venv.Lib.site-packages.sympy.concrete.tests',
              'venv.Lib.site-packages.sympy.diffgeom', 'venv.Lib.site-packages.sympy.diffgeom.tests',
              'venv.Lib.site-packages.sympy.discrete', 'venv.Lib.site-packages.sympy.discrete.tests',
              'venv.Lib.site-packages.sympy.external', 'venv.Lib.site-packages.sympy.external.tests',
              'venv.Lib.site-packages.sympy.geometry', 'venv.Lib.site-packages.sympy.geometry.tests',
              'venv.Lib.site-packages.sympy.matrices', 'venv.Lib.site-packages.sympy.matrices.tests',
              'venv.Lib.site-packages.sympy.matrices.benchmarks', 'venv.Lib.site-packages.sympy.matrices.expressions',
              'venv.Lib.site-packages.sympy.matrices.expressions.tests', 'venv.Lib.site-packages.sympy.plotting',
              'venv.Lib.site-packages.sympy.plotting.tests', 'venv.Lib.site-packages.sympy.plotting.pygletplot',
              'venv.Lib.site-packages.sympy.plotting.pygletplot.tests',
              'venv.Lib.site-packages.sympy.plotting.intervalmath',
              'venv.Lib.site-packages.sympy.plotting.intervalmath.tests', 'venv.Lib.site-packages.sympy.printing',
              'venv.Lib.site-packages.sympy.printing.tests', 'venv.Lib.site-packages.sympy.printing.pretty',
              'venv.Lib.site-packages.sympy.printing.pretty.tests', 'venv.Lib.site-packages.sympy.simplify',
              'venv.Lib.site-packages.sympy.simplify.tests', 'venv.Lib.site-packages.sympy.functions',
              'venv.Lib.site-packages.sympy.functions.special', 'venv.Lib.site-packages.sympy.functions.special.tests',
              'venv.Lib.site-packages.sympy.functions.special.benchmarks',
              'venv.Lib.site-packages.sympy.functions.elementary',
              'venv.Lib.site-packages.sympy.functions.elementary.tests',
              'venv.Lib.site-packages.sympy.functions.elementary.benchmarks',
              'venv.Lib.site-packages.sympy.functions.combinatorial',
              'venv.Lib.site-packages.sympy.functions.combinatorial.tests', 'venv.Lib.site-packages.sympy.holonomic',
              'venv.Lib.site-packages.sympy.holonomic.tests', 'venv.Lib.site-packages.sympy.integrals',
              'venv.Lib.site-packages.sympy.integrals.rubi', 'venv.Lib.site-packages.sympy.integrals.rubi.rules',
              'venv.Lib.site-packages.sympy.integrals.rubi.tests',
              'venv.Lib.site-packages.sympy.integrals.rubi.parsetools',
              'venv.Lib.site-packages.sympy.integrals.rubi.parsetools.tests',
              'venv.Lib.site-packages.sympy.integrals.rubi.rubi_tests',
              'venv.Lib.site-packages.sympy.integrals.rubi.rubi_tests.tests',
              'venv.Lib.site-packages.sympy.integrals.tests', 'venv.Lib.site-packages.sympy.integrals.benchmarks',
              'venv.Lib.site-packages.sympy.utilities', 'venv.Lib.site-packages.sympy.utilities.tests',
              'venv.Lib.site-packages.sympy.utilities.mathml', 'venv.Lib.site-packages.sympy.utilities._compilation',
              'venv.Lib.site-packages.sympy.utilities._compilation.tests', 'venv.Lib.site-packages.sympy.benchmarks',
              'venv.Lib.site-packages.sympy.categories', 'venv.Lib.site-packages.sympy.categories.tests',
              'venv.Lib.site-packages.sympy.deprecated', 'venv.Lib.site-packages.sympy.deprecated.tests',
              'venv.Lib.site-packages.sympy.strategies', 'venv.Lib.site-packages.sympy.strategies.tests',
              'venv.Lib.site-packages.sympy.strategies.branch', 'venv.Lib.site-packages.sympy.strategies.branch.tests',
              'venv.Lib.site-packages.sympy.assumptions', 'venv.Lib.site-packages.sympy.assumptions.tests',
              'venv.Lib.site-packages.sympy.assumptions.handlers', 'venv.Lib.site-packages.sympy.interactive',
              'venv.Lib.site-packages.sympy.interactive.tests', 'venv.Lib.site-packages.sympy.liealgebras',
              'venv.Lib.site-packages.sympy.liealgebras.tests', 'venv.Lib.site-packages.sympy.combinatorics',
              'venv.Lib.site-packages.sympy.combinatorics.tests', 'venv.Lib.site-packages.sympy.multipledispatch',
              'venv.Lib.site-packages.sympy.multipledispatch.tests', 'venv.Lib.site-packages.mpmath',
              'venv.Lib.site-packages.mpmath.libmp', 'venv.Lib.site-packages.mpmath.tests',
              'venv.Lib.site-packages.mpmath.calculus', 'venv.Lib.site-packages.mpmath.matrices',
              'venv.Lib.site-packages.mpmath.functions', 'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='Qingchun Wang',
    author_email='qingchun720@foxmail.com',
    description='auto gvb'
)
